ARG BASE_IMAGE=ubuntu:18.04
FROM --platform=$TARGETPLATFORM $BASE_IMAGE

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8

RUN set -ex \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        libbz2-dev \
        libffi-dev \
        libgdbm-dev \
        libncurses5-dev \
        libnss3-dev \
        libreadline-dev \
        libsqlite3-dev \
        libssl-dev \
        wget \
        xz-utils \
        zlib1g-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ARG PYTHON_INSTALL_PREFIX=/src/python
RUN mkdir -p $PYTHON_INSTALL_PREFIX

ARG PYTHON_VERSION=3.12.3

RUN set -ex \
    && wget -O python.tar.xz --no-check-certificate "https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tar.xz" \
    && tar -xf python.tar.xz \
    && rm python.tar.xz \
    && cd Python-$PYTHON_VERSION/ \
    && ./configure \
        --build="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)" \
        --prefix=$PYTHON_INSTALL_PREFIX \
        --enable-optimizations \
    && make -j $(nproc) \
    && make altinstall \
    && rm -rf /Python-$PYTHON_VERSION

WORKDIR $PYTHON_INSTALL_PREFIX
